---
abstract: 'Perl interface to libnotify'
author:
  - 'Florian Ragwitz, C<< <rafl at debian.org> >>'
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::PkgConfig: 0
  Glib::MakeHelper: 0
  Gtk2::CodeGen: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk2-Notify
no_index:
  directory:
    - inc
    - ext
    - inc
    - t
    - examples
requires:
  Gtk2: 0
version: 0.05
