--- #YAML:1.0
name:                Gtk2-Notify
version:             0.03
abstract:            Perl interface to libnotify
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Glib:                          1.093
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Florian Ragwitz <rafl@debian.org>
